apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: mybookstore
data:
  rabbitmq.conf: |
    vm_memory_high_watermark.relative = 0.4
    disk_free_limit.absolute = 50MB
    management.load_definitions = /etc/rabbitmq/definitions.json
  definitions.json: |
    {
      "users": [
        {
          "name": "guest",
          "password": "guest",
          "tags": "administrator"
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "permissions": [
        {
          "user": "guest",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ]
    }