apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: mybookstore
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  ports:
  - port: 5672
    targetPort: 5672
    name: amqp
  - port: 15672
    targetPort: 15672
    name: management
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: mybookstore
  labels:
    app: rabbitmq
spec:
  type: NodePort
  ports:
  - port: 15672
    targetPort: 15672
    nodePort: 30672
    name: management
  selector:
    app: rabbitmq