apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mybookstore-cluster
  region: us-east-1
  version: "1.28"

availabilityZones: ["us-east-1a","us-east-1b","us-east-1c"]

kubernetesNetworkConfig:
  ipFamily: IPv4
iam:
  withOIDC: true

vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: Single
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

managedNodeGroups:
  - name: mybookstore-nodes
    instanceType: t3.small
    desiredCapacity: 3        
    minSize: 0                
    maxSize: 10
    privateNetworking: false  # nodos en subred pública con ExternalIP (para NodePort)
    volumeSize: 20
    labels:
      role: app
    ssh:
      allow: false
    tags:
      alpha.eksctl.io/cluster-name: mybookstore-cluster
      alpha.eksctl.io/nodegroup-name: mybookstore-nodes