apiVersion: v1
kind: Service
metadata:
  name: frontend-order
  namespace: mybookstore
  labels:
    app: frontend-order
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8083
    targetPort: 8083
    nodePort: 30083
    name: http
  selector:
    app: frontend-order