apiVersion: v1
kind: Service
metadata:
  name: frontend-payment
  namespace: mybookstore
  labels:
    app: frontend-payment
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8084
    targetPort: 8084
    nodePort: 30084
    name: http
  selector:
    app: frontend-payment