apiVersion: v1
kind: Service
metadata:
  name: frontend-catalog
  namespace: mybookstore
  labels:
    app: frontend-catalog
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
    name: http
  selector:
    app: frontend-catalog