apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: mybookstore
  labels:
    app: cart
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 50050
    targetPort: 50050
    name: grpc
  selector:
    app: cart