apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: mybookstore
  labels:
    app: catalog
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051
    name: grpc
  selector:
    app: catalog