apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: mybookstore
  labels:
    app: catalog
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
        tier: backend
    spec:
      containers:
      - name: catalog
        image: mybookstore-catalog-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
          name: grpc
        envFrom:
        - configMapRef:
            name: mybookstore-config
        volumeMounts:
        - name: catalog-storage
          mountPath: /data
        livenessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: catalog-storage
        emptyDir: {}