apiVersion: v1
kind: Service
metadata:
  name: inventory
  namespace: mybookstore
  labels:
    app: inventory
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 50052
    targetPort: 50052
    name: grpc
  selector:
    app: inventory