apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: mybookstore
  labels:
    app: order
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 50054
    targetPort: 50054
    name: grpc
  selector:
    app: order