apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: mybookstore
  labels:
    app: order
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
        tier: backend
    spec:
      containers:
      - name: order
        image: mybookstore-order-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50053
          name: grpc
        envFrom:
        - configMapRef:
            name: mybookstore-config
        volumeMounts:
        - name: order-storage
          mountPath: /data
        livenessProbe:
          tcpSocket:
            port: 50053
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 50053
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: order-storage
        emptyDir: {}