apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: mybookstore
  labels:
    app: payment
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 50053
    targetPort: 50053
    name: grpc
  selector:
    app: payment