apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: mybookstore
  labels:
    app: user
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 50055
    targetPort: 50055
    name: grpc
  selector:
    app: user